projektBSI/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using projektBSI.DataAccessLayer;
using projektBSI.Entities;
using projektBSI.Models;

namespace projektBSI.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }
        [Authorize]
        public ActionResult List()
        {
            string id = User.Identity.GetUserId();
            var posts = from x in db.Posts.Where(x => x.ApplicationUser.Id == id)
                           select new PostModel()
                           {
                               Id = x.Id,
                               Title = x.Title,
                               Article = x.Article,
                               UserId = x.UserId,
                               ApplicationUser = x.ApplicationUser,
                               Signature = x.ApplicationUser.Signature
                           };
            if (User.IsInRole("Admin"))
            {
                posts = from x in db.Posts
                        select new PostModel()
                        {
                            Id = x.Id,
                            Title = x.Title,
                            Article = x.Article,
                            UserId = x.UserId,
                            ApplicationUser = x.ApplicationUser,
                            Signature = x.ApplicationUser.Signature
                        };
            }
            return View(posts);
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Title,Article")] Post post, String UserId)
        {
            var userID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                var postToAdd = new Post
                {
                    Id = post.Id,
                    Title = post.Title,
                    Article = post.Article,
                    UserId = User.Identity.GetUserId(),
                    DateOfPublication = DateTime.Now
                };
                db.Posts.Add(postToAdd);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(post);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Article")] Post post)
        {
            if (ModelState.IsValid)
            {
                var postToAdd = new Post
                {
                    Id = post.Id,
                    Title = post.Title,
                    Article = post.Article,
                    UserId = post.UserId,
                    DateOfPublication = post.DateOfPublication
                };
                db.Entry(postToAdd).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
        [Authorize]
        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

projektBSI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="main-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p id="logo">@Html.ActionLink("ProjektBSI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Strona główna", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @*<li>@Html.ActionLink("Wpisy", "Index" , "Posts")</li>*@

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — Strona stworzona jako projekt zaliczeniowy przedmiotu "Budowa Serwisów Internetowych" przez Marcina Zemło</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>